Libraries/CameraRoll/RCTImagePickerManager.m
Currently `ImagePickerIOS` does not return a width or height for videos selected in the Photo Library. This change patches our RN repo to grab the width and height data from the PHAsset and return it to JS through ImagePickerIOS. 
This code was shamelessly stolen from Expo, who already handles this case:
https://github.com/expo/expo/blob/master/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m#L297
=> patch ImagePickerIOS to return video width and height

Libraries/CameraRoll/RCTImagePickerManager.m
original PR was #2, redoing this to merge it into .59
=> patch imagepickerios video widths

Libraries/Text/Text/RCTTextShadowView.m
iOS13 puts a placeholder behind `Image` components within `Text`
Before:
After:
=> placeholder image patch

React/Modules/RCTStatusBarManager.m
We cherry-pick this commit https://github.com/facebook/react-native/commit/796b3a1f8823c87c9a066ea9c51244710dc0b9b5 to fix dark theme status bar
Summary:
iOS13 status bar has now 3 styles
UIStatusBarStyleDefault, UIStatusBarStyleLightContent, UIStatusBarStyleDarkContent
UIStatusBarStyleDefault now acts as an automatic style which will set it’s value dynamically based on the the userinterfacestyle(One of the traits) of the viewcontroller that controls the status bar appearance.
[iOS] [Fixed] - iOS13 new status bar style UIStatusBarStyleDarkContent
Pull Request resolved: https://github.com/facebook/react-native/pull/26294
Differential Revision: D17314054
Pulled By: cpojer
fbshipit-source-id: ea109e729bb551dff314bc00a056860a8febb0e9
[CATEGORY] [TYPE] - Message
=> iOS13 status bar has now 3 styles (#26294)

React/Modules/RCTStatusBarManager.m
Cherry-picked facebook commit https://github.com/facebook/react-native/commit/796b3a1f8823c87c9a066ea9c51244710dc0b9b5 to fix dark mode status bar
=> iOS13 status bar has now 3 styles

ReactAndroid/build.gradle, ReactAndroid/gradle.properties, discord/bump_version.py
a few changes to enable publishing to our internal repository.
run `discord/bump_version.py`, it'll ensure the repo is clean, update the version as expected and publish the artifact.
=> [rna] add package publishing support

ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/ImageOTAUtils.java, ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/PhoneDensity.java, ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/ResourceDrawableIdHelper.java, ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
Modify `ResourceDrawableIdHelper` to look first in the cache to see if there are any ota images before looking it up in the resource map.
=> [RNA][OTA] Adding image support

React/Views/RCTSwitchManager.m
Currently, the switch does not animate when its value changes. This makes it jank when we try to programmatically toggle it by changing its value. For example, I want to allow toggling the switch by pressing it's label (https://github.com/discord/discord/pull/67835) but since the switch doesn't animate when the value changes, the interaction looks horrible. 
This PR makes it so that the switch animates when its value changes. The current switch code maps the `on` value of the switch to the value passed in from JS. However, setting the `on` value this way does not animate.
```
RCT_REMAP_VIEW_PROPERTY(value, on, BOOL);
```
To fix that, I replaced it with
```
RCT_CUSTOM_VIEW_PROPERTY(value, BOOL, RCTSwitch)
{
if (json) {
BOOL on = [RCTConvert BOOL:json];
if (view.wasOn != on) {
[(UISwitch …
```
=> animate switch on value change

ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java, ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditTextClickDetector.java
There is a tracked issue in react native where on Android 7/8/9 (and maybe lower), the keyboard will not show up if an already-focused ReactEditText is clicked: https://github.com/facebook/react-native/issues/31374
this is easy to repro by dismissing the keyboard using the system back button, then trying to click the edittext.
this PR fixes that by detecting clicks on the view and forcing the keyboard to show if on android 9 or lower.
i'm sure there will be downsides to this approach but i think it gets us out the door for rna.
=> Android 7/8/9: force keyboard to show when ReactEditText is clicked

Libraries/WebSocket/RCTSRWebSocket.h, Libraries/WebSocket/RCTSRWebSocket.m, React/CoreModules/RCTWebSocketModule.h, React/CoreModules/RCTWebSocketModule.mm
There was a bit of plumbing to do as there were multiple assertions done along the way to ensure this work is done on the workQueue thread.
I tested this out by adding a sleep of 2 seconds inside closeWithCode block. Seems to work fine.
See:  https://www.notion.so/discordapp/RFC-Mobile-Gracefully-closing-the-Gateway-Socket-on-App-Termination-69b44fb46f4e4fedbbca7102e9e2ac29 for more info
=> expose `flush` on RCTWebSocketModule to close all open websockets synchronously

ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java
Oops -- didn't test it with a few changes, ended up having to go with the third option in that previous comment.
=> fix clipping issue

Libraries/Components/Pressable/useAndroidRippleForView.js, Libraries/Components/View/ViewPropTypes.js, ReactAndroid/src/main/java/com/facebook/react/views/view/ReactDrawableHelper.java
**In This PR..**
Adding `cornerRadius` to `Pressable` `RippleConfig`
This is part of the `Pressable` refactor saga, which began here:
https://github.com/discord/discord/pull/73789
The above PR made it so we masked the `Pressable` at the Javascript level; nesting the `Pressable` in a `View` with `overflow: hidden` and its corner radii defined, and having the `children` be sibling to the `Pressable` instead of actually as `children`. This unfortunately broke screen readers, so the sibling part of the PR has since been reverted here: https://github.com/discord/discord/pull/76318
Now, instead of masking at the Javascript level, we're masking at the Java level. **This PR does not change the look of any ripples in the app.** Though I have tested that setting `cornerRadius` does correctly set …
=> Adding cornerRadius to Pressable RippleConfig

ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLineHeightSpan.java
Fixing an issue where RNA would purposely shift text to respect lineHeights. See comments in code for more explanation.
See https://www.notion.so/discordapp/Line-Break-Before-After-aa67103b451f48d09267c2ab19e0b53d for comparison of before/afters
=> [RNA] Align text

ReactAndroid/src/main/java/com/facebook/react/modules/accessibilityinfo/AccessibilityInfoModule.java
this is an attempt to fix this issue on our fork: https://github.com/facebook/react-native/issues/31221
homie in [this comment](https://github.com/facebook/react-native/issues/31221#issuecomment-1114365526) has identified a fix. the tl;dr is that the react native code was checking to see if the value (as a string) was "`0.0`", but it's more appropriate to check against the float value (because it is possible that the string was set to something else, like just `"0"`.
i have confirmed that this fixes the root-cause bug of RN not reading this setting properly.
=> Fix android reduced motion accessibility setting

ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java
This is a simple change to ignore the way that RN's Android code searches for fonts with a `_bold`, `_italic`, or `_bold_italic` suffix in their filename. In Discord's codebase we just declare the font family, but some of our libraries don't just do that.
We'll need to revert this change once we rework how we do fonts on RN (since currently we're a bit off-book).
=> Remove RN Android's bizarre font weight extension pattern

packages/react-native-codegen/src/generators/modules/GenerateModuleJniH.js, packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt
**In This PR..**
Adding Support for building only Discord TurboModules.
We accomplish in two parts (TL;DRs in bold)
1. **Adding an option in `ReactPlugin.kt` to codegen only modules with a package name starting with `com.discord`.** Codegen is the "third pillar" of "The New Architecture". It allows us to define the schema of what's communicated through the JSI, and have the Makefiles/Java/etc. generated for us, to the point where all we need to do is include and implement their generated interface on the native side, and call the generated interface from the JS side. The vanilla way to codegen is by running the `generateCodegenArtifactsFromSchema` gradle task with `newArchEnabled=true`, normally this task is added as part of the build when `newArchEnabled=true`, so it's not normally run …
=> Adding Discord-only TurboModule support

ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java, packages/rn-tester/js/examples/Accessibility/AccessibilityAndroidExample.android.js
This is a local PR for https://github.com/facebook/react-native/pull/37050 submitted against upstream, since they're taking their sweet time with it. Original PR description with context:
If an accessible link is ellipsized out of being rendered, the AccessibilityDelegate will still attempt to populate an accessibility node for it; doing so results in an invalid request to a TextLayout API, however, causing a crash. This crash occurs as soon as the element is rendered, so long as a Screen Reader (or app using similar a11y APIs) is enabled. This change uses a technique similar to those existing to make the node "blank" in such cases, so Talkback can filter it out—and, more importantly, not crash.
[Android] [Fixed] - Fix links hidden via ellipsis crashing screen readers
- Added a block to …
=> Fix: a11y crash when an accessible link is ellipsized away

packages/virtualized-lists/Lists/VirtualizedList.js
Asana: https://app.asana.com/0/1199167684846005/1205213585978357
This PR cherry-picks the fix from origin react native repo and adds clamp for `last` prop so it won't be less than -1.
=> Clamp `last` of cellsAroundViewport

ReactAndroid/build.gradle
Fixes build on Linux / WSL.
Currently the build on linux is failing.
The error I get is:
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ReactNativeSource:prepareBoost'.
> Could not expand ZIP '/home/alex/dev/discord/discord_app/node_modules/react-native/ReactAndroid/build/downloads/boost_1_81_0.zip'.
```
Building with tracing I see:
```
Caused by: java.lang.IllegalArgumentException: 'boost_1_81_0/libs/json/test/parse-vectors/n_number_-1.0..json' is not a safe zip entry name.
at org.gradle.util.internal.ZipSlip.safeZipEntryName(ZipSlip.java:37)
```
This seems to be a failure to unpack the boost zip due to gradle "ZipSlip" mitigations.  
Question: Do we still need the regular zip anywhere?
[ANDROID] Use boost tar instead of zip on linux
I …
=> use boost tar on linux too

Libraries/Animated/NativeFabricMeasurerTurboModule.js, ReactAndroid/src/main/java/com/facebook/react/animated/NativeFabricMeasurerModule.java, ReactAndroid/src/main/java/com/facebook/react/shell/MainReactPackage.java, ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewMeasurer.java, ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp
**In This PR..**
A fix for measuring native views in Fabric.
Starting in Fabric, React Native has a "Shadow Tree". Its state is kept in C++. The Shadow Tree is the Native representation of React's JS component tree. The Shadow Tree differs from React's JS component tree in two main ways.
1) The Shadow tree only contains the components that reduce to actual Native views. For example, if you had a
`<MyCoolComponent style={...}><View /></MyCoolComponent>` in JS,
the Shadow Tree would only contain `View` because `MyCoolComponent` does not have a Native representation (unless you added a native `ViewManager` for `MyCoolComponent` and registered that natively ahead of time, but we're assuming here the only reference to `MyCoolComponent` is in JS).
2) The Shadow Tree contains every view's layout …
=> NativeMeasurer for Android

ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java
Why is this broken, tldr? Both paper and fabric start with the wrong value from ModalHostHelper, and both get on size changed callbacks from the android OS for the view with correct sizing. Paper uses this and the size becomes the source of truth & is reflected in the shadow tree. Fabric sets the state on the shadow tree which triggers an update state callback (specific to fabric) which then gets the wrong size from modal host helper again and overwrites the correct size.
1. Delete modal host helper (like the pr from sw mansion engineer). Causes freezes deep in fabric renderer caused by views starting with zero size. This bug was mistakenly introduced by fb fixing this. ❌
2. Update ModalHostHelper to return the correct sizes. This file hasn't changed in 4 years and is easier said than …
=> Fix incorrect values for modal sizing

Libraries/WebSocket/WebSocket.js
This adds an extra 'raw_length' field to WebSocketEvent that propagates it from the webSocketMessage from the underlying websocket implementation. It is intended to be used to measure the compressed size of the payload.
=> support websocket raw length

ReactAndroid/src/main/java/com/facebook/react/devsupport/DevSupportManagerBase.java
Analogous to https://github.com/facebook/react-native/pull/38256
This adds a compatibility support method `compatRegisterReceiver` to support new changes in android 14 around broadcast receivers.
from the upstream PR: 
Summary:
Add RECEIVER_EXPORTED/RECEIVER_NOT_EXPORTED flag support to DevSupportManagerBase for Android 14 change. See
https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported for details.
Without this fix, app crashes during launch because of :
SecurityException: {package name here}: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
Differential Revision: D47313501
=> Adds Android 14 support to DevSupportManagerBase

scripts/ios-configure-glog.sh
Xcode 15's version of gcc seems to break the build of `glog` (a dependency of React Native). Since we run `pod install` inside of a Nix shell, though, I feel pretty safe falling back to the environment's gcc (rather than using Xcode's). 
I can only assume that RN was doing this to try to make the compilation more hermetic, but we are already wrapping it in a hermetic environment.
=> Avoid using Xcode 15's gcc when compiling glog

packages/react-native/Libraries/Text/BaseText/RCTBaseTextViewManager.mm, packages/react-native/Libraries/Text/RCTTextAttributes.h, packages/react-native/Libraries/Text/RCTTextAttributes.mm, packages/react-native/Libraries/Text/Text.d.ts, packages/react-native/Libraries/Text/TextNativeComponent.js, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/internal/span/LinearGradientSpan.kt
We added a new Boost perk called "Enhanced Role Colors/Styles" that allows admins to set gradient colors for roles in their guild. To support this on mobile, we have to provide native components that can render gradients.
At first, we were planning to create a custom native component but ran into 2 issues:
1. The custom component [needed a `height` and `width`](https://canary.discord.com/channels/281683040739262465/1352018048835522743/1354224981629866106) defined for it to render. This was fixed by [using a `ShadowNode`](https://canary.discord.com/channels/281683040739262465/1352018048835522743/1354474720615207152) but we ran into other sizing issues.
2. Our string formatter [nests `Text` nodes](https://canary.discord.com/channels/281683040739262465/1352018048835522743/1355183603725762752) …
=> update Text to support gradient colors

packages/react-native/Libraries/Text/RCTTextAttributes.mm
When we added gradient colors to `Text` in https://github.com/discord/react-native/pull/54, we forgot to duplicate the first color to create a mirrored pattern. Without the duplicated first color, the color transitions abruptly from the last color back to the first color.
- duplicate first color when we create gradient color for `Text`
- Tested the chat input context bar which is the only component actively using this gradient
=> update Text gradient colors to be mirrored on ios

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/internal/span/LinearGradientSpan.kt
This PR fixes gradient colors on text appearing "faded". The *exact* reason isn't known but I found this [relevant stackoverflow answer](https://stackoverflow.com/a/52289927) and testing out the change shows that it works.
- updated span operation logic to set a color span *and* a gradient color span if both are passed in (though visually the gradient color span takes precedence since it updates the shader itself)
- updated `LinearGradientSpan` to call `setColor` on the first color too -> this is needed when a color isn't set such as when `color="none"` is passed from the React JS side
- tested guild member list
- tested setting a random `Text` component with gradient colors
**Guild member list**
_before_
_after_
**Thread title**
_before_
_after_
=> fix android gradient colors faded

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/appstate/AppStateModule.kt
During app startup, react-native's `AppState.currentState` can incorrectly report `background` when the app is actually in the foreground. This happens because:
1. `AppStateModule` relies on `onHostResume` and `onHostPause` event subscriptions to track state
2. The initial state can incorrectly initialize to `APP_STATE_BACKGROUND` when `reactContext.lifecycleState === LifecycleState.BEFORE_CREATE` (which occurs before root view attachment)
This PR adds an `isAppForegroundedByMemoryState()` method that provides a more accurate initial state detection when the React context is in `BEFORE_CREATE` lifecycle state.
While this is a quick workaround to address the immediate issue, potential future improvements:
1. Leveraging Android activity lifecycle to set initial state to `RESUMED` on …
=> [android] harden AppStateModule initial state

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/defaults/DefaultNewArchitectureEntryPoint.kt, packages/react-native/ReactCommon/react/renderer/core/ShadowNode.cpp, packages/react-native/ReactCommon/react/renderer/core/ShadowNode.h, packages/react-native/ReactCommon/react/renderer/mounting/updateMountedFlag.cpp
We merged RN 0.78 into the upgrade/new-arch branch.
We need to enable react shadow node runtime updates (RSNRU) to avoid inconsistencies between the JS react fiber tree and the shadow tree on the UI thread.
=> new arch rn078 fixes

packages/react-native/ReactCommon/react/renderer/components/view/platform/android/react/renderer/components/view/HostPlatformViewProps.cpp, packages/react-native/ReactCommon/react/renderer/components/view/platform/android/react/renderer/components/view/HostPlatformViewProps.h
This cherry-picks this PR on top of our RN 0.78 branch to fix some rendering issues happening on new arch:
- https://github.com/facebook/react-native/pull/45552
When using FlashList with new arch on our RN 0.78 build we were seeing weird layout bugs:
- https://github.com/Shopify/flash-list/issues/1576#issue-2942491997
after testing we found that on RN 0.79 these issues don't happen. I ran a bisect and found that this commit fixes the issue.
Now, its odd that this commit is fixing the issue, as the function `getDiffProps` is nowhere called during runtime! (There is one call site in `android/FabricMountingManager.cpp` but thats behind a feature flag that is false).
My best assumption is that in release mode (the only place where the bug happens) some optimization flags are applied which …
=> Introduce getDiffProps for <View> (#45552)

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.kt, packages/react-native/ReactCommon/react/renderer/components/modal/CMakeLists.txt, packages/react-native/ReactCommon/react/renderer/components/modal/ModalHostViewState.h, packages/react-native/ReactCommon/react/renderer/components/modal/platform/android/JReactModalHostView.h, packages/react-native/ReactCommon/react/renderer/components/modal/platform/android/ModalHostViewUtils.cpp
This fixes a frozen UI bug caused by the Modal's broken layout. We are pulling a [soon to land patch](https://github.com/facebook/react-native/pull/51048/files) in the React Native core repo. Once we upgrade to a version that includes this patch this will naturally merge.
| Before | After |
|--|--|
| <video width="300" src="https://github.com/user-attachments/assets/a0c1876a-eaf4-4ae7-8ce9-a5bbe6cbd596" /> |  <video width="300" src="https://github.com/user-attachments/assets/f841d3de-d906-44dc-b138-66c084ceaf35" />  |
| Before | After |
|--|--|
| <video width="300" src="https://github.com/user-attachments/assets/854452d7-1205-4ede-84ec-ff2f73383685"></video> |  <video width="300" src="https://github.com/user-attachments/assets/d6139ff5-e614-4f0e-8e50-0a41ee050cd5" />  |
=> patch ReactModalHostview to init with correct sizes

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlags.kt, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxAccessor.kt, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxInterop.kt, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsDefaults.kt, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsLocalAccessor.kt, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsProvider.kt, packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.cpp, packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.h, packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.cpp, packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.h, packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.cpp, packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.h, packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDefaults.h, packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDynamicProvider.h, packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsProvider.h, packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.cpp, packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.h, packages/react-native/ReactCommon/react/renderer/core/ShadowNode.cpp, packages/react-native/scripts/featureflags/ReactNativeFeatureFlags.config.js, packages/react-native/src/private/featureflags/ReactNativeFeatureFlags.js, packages/react-native/src/private/featureflags/specs/NativeReactNativeFeatureFlags.js
This applies changes from RN 0.79 that fix buggy behaviour.
Specifically picking this change:
- https://github.com/facebook/react-native/commit/96939f160b169db422f5d85085375c3cc712345f
This avoids state updates being dropped, which causes all kind of bugs
=> fix shadow node state updates
